### ISSUE TITLE
Error launching prosodyctl.sh

### ISSUE THREAD

**Issue by nicfab** [JohnXLivingston/peertube-plugin-livechat#180]
After launching `prosody.sh` that is under `/etc/letsencrypt/renewal-hooks/deploy` I receive the following error:

```
/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosodyAppImage/squashfs-root/usr/bin/lua5.2: /usr/bin/prosodyctl:635: /usr/lib/prosody/util/prosodyctl/cert.lua:182: Failed to change ownership of /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/certs/tube.nicfab.eu.crt
stack traceback:
	[C]: in function 'assert'
	/usr/lib/prosody/util/prosodyctl/cert.lua:182: in function 'copy'
	/usr/lib/prosody/util/prosodyctl/cert.lua:243: in function </usr/lib/prosody/util/prosodyctl/cert.lua:188>
	(...tail calls...)
	/usr/bin/prosodyctl:751: in function 'func'
	/usr/lib/prosody/util/async.lua:144: in function </usr/lib/prosody/util/async.lua:142>
stack traceback:
	[C]: in function 'error'
	/usr/bin/prosodyctl:635: in function 'handler'
	/usr/lib/prosody/util/async.lua:232: in function 'run'
	/usr/bin/prosodyctl:754: in main chunk
	[C]: in function 'dofile'
	...echat/prosodyAppImage/squashfs-root/usr/bin/launcher.lua:25: in main chunk
	[C]: in ?

```

**Comment by JohnXLivingston** [comment]
Note for myself: it is on ubuntu.

**Comment by nicfab** [comment]
I changed the prosody ports, and particularly:

- instead of 52800 another port
- instead of 52802 another port

Now, launching the diagnostic I see the following:

```
Diagnostic

    Starting tests: OK
    Browser: OK
    Backend connection: OK
    Test debug mode: OK
        Debug mode is OFF
    Webchat activated on videos: OK
        Chat will open automatically
        Displaying «open in new window» button
        Chat can be enabled on live videos.
        Chat is enabled for all lives.
        Chat is enabled for all non-lives.
    Builtin Prosody and ConverseJS: OK
        The working dir is: /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody
        Prosody will run on port '7750'
        Prosody will use https://tube.nicfab.eu/plugins/livechat/7.0.1/router/api/ as base uri from api calls
        Prosody path will be '/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosodyAppImage/squashfs-root/AppRun'
        Prosody will be using the '/var/www/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody/livechat-prosody-x86_64.AppImage' AppImage
        Prosody AppImage extract path will be '/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosodyAppImage'
        Prosody modules path will be '/var/www/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules'
        Prosody rooms will be grouped by 'video'.
        By default, room content will be archived.
        Room content will be saved for '1m'
        The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
        Prosody configuration file content is correct.
        Pid file /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.pid found
        Prosodyctl status: Prosody is running with PID 69111
        The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
        Prosody configuration file content is correct.
        No missing self signed certificates.
        Prosody version is 0.12.3
        API Peertube -> Prosody is OK
        API Prosody -> Peertube is OK
        The prosody error log (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.err) exists

Additional debugging information
Current prosody configuration
daemonize = false;
allow_registration = false;
admins = {
};
pidfile = "/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.pid";
plugin_paths = {
  "/var/www/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules";
};
data_path = "/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/data";
storage = "internal";
modules_enabled = {
  "roster";
  "saslauth";
  "carbons";
  "version";
  "uptime";
  "ping";
  "bosh";
  "posix";
  "disco";
  "s2s";
  "tls";
  "s2s_peertubelivechat";
  "websocket_s2s_peertubelivechat";
};
modules_disabled = {
};
consider_bosh_secure = true;
consider_websocket_secure = true;
certificates = "/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/certs";
c2s_require_encryption = false;
interfaces = {
  "127.0.0.1";
  "::1";
};
c2s_ports = {
  "7752";
};
c2s_interfaces = {
  "127.0.0.1";
  "::1";
};
s2s_ports = {
  "52690";
};
s2s_interfaces = {
  "*";
  "::";
};
http_ports = {
  "7750";
};
http_interfaces = {
  "127.0.0.1";
  "::1";
};
https_ports = {
};
https_interfaces = {
  "127.0.0.1";
  "::1";
};
trusted_proxies = {
  "127.0.0.1";
  "::1";
};
c2s_close_timeout = 29;
s2s_secure_auth = false;
peertubelivechat_server_infos_path = "/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/serverInfos";
peertubelivechat_instance_url = "https://tube.nicfab.eu";
websocket_s2s_ping_interval = 55;
s2s_peertubelivechat_no_outgoing_directs2s_to_peertube = false;
log = {
  info = "/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.log";
  error = "/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.err";

};



VirtualHost "tube.nicfab.eu"
  authentication = "http";
  modules_enabled = {
  "ping";
  "http";
  "bosh";
  "websocket";
  "dialback";
  "vcard_peertubelivechat";
};
  http_auth_url = "https://tube.nicfab.eu/plugins/livechat/7.0.1/router/api/user";
  allow_anonymous_s2s = false;
  http_host = "tube.nicfab.eu";
  http_external_url = "http://tube.nicfab.eu";
  peertubelivechat_vcard_peertube_url = "https://tube.nicfab.eu";


VirtualHost "anon.tube.nicfab.eu"
  authentication = "anonymous";
  modules_enabled = {
  "ping";
  "http";
  "bosh";
  "websocket";
  "random_vcard_peertubelivechat";
};
  allow_anonymous_s2s = false;
  http_host = "tube.nicfab.eu";
  http_external_url = "http://tube.nicfab.eu";
  peertubelivechat_random_vcard_avatars_path = "/var/www/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/avatars";


Component "room.tube.nicfab.eu" "muc"
  muc_room_locking = false;
  muc_tombstones = false;
  muc_room_default_language = "en";
  muc_room_default_public = false;
  muc_room_default_persistent = true;
  muc_room_default_members_only = false;
  muc_room_default_moderated = false;
  muc_room_default_public_jids = false;
  muc_room_default_change_subject = false;
  muc_room_default_history_length = 20;
  restrict_room_creation = false;
  http_host = "tube.nicfab.eu";
  http_external_url = "http://tube.nicfab.eu";
  modules_enabled = {
  "muc_http_defaults";
  "websocket_s2s_peertubelivechat";
  "dialback";
  "muc_mam";
  "muc_moderation";
  "http_peertubelivechat_list_rooms";
  "http_peertubelivechat_test";
};
  muc_create_api_url = {
  "https://tube.nicfab.eu/plugins/livechat/7.0.1/router/api/room?apikey=***APIKey***&jid={room.jid|jid_node}";
};
  muc_log_by_default = true;
  muc_log_presences = true;
  log_all_rooms = false;
  muc_log_expires_after = "1m";
  muc_log_cleanup_interval = 14400;
  peertubelivechat_list_rooms_apikey = "***APIKey***";
  peertubelivechat_test_apikey = "***APIKey***";
  peertubelivechat_test_peertube_api_url = "https://tube.nicfab.eu/plugins/livechat/7.0.1/router/api/test?apikey=***APIKey***";


Prosody version
Prosody 0.12.3

# Prosody directories
Data directory:     /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/data
Config directory:   /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody
Source directory:   /usr/lib/prosody
Plugin directories:
  /var/lib/prosody/custom_plugins - not a directory!
  /var/www/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules
  /usr/lib/prosody/modules/
  

# Operating system
Linux 5.15.0-1037-aws	

# Lua environment
Lua version:             	Lua 5.2

Lua module search paths:
  /usr/lib/prosody/?.lua
  /usr/local/share/lua/5.2/?.lua
  /usr/local/share/lua/5.2/?/init.lua
  /usr/local/lib/lua/5.2/?.lua
  /usr/local/lib/lua/5.2/?/init.lua
  /usr/share/lua/5.2/?.lua
  /usr/share/lua/5.2/?/init.lua
  /var/lib/prosody/custom_plugins/share/lua/5.2/?.lua
  /var/lib/prosody/custom_plugins/share/lua/5.2/?/init.lua

Lua C module search paths:
  /usr/lib/prosody/?.so
  /usr/local/lib/lua/5.2/?.so
  /usr/lib/x86_64-linux-gnu/lua/5.2/?.so
  /usr/lib/lua/5.2/?.so
  /usr/local/lib/lua/5.2/loadall.so

LuaRocks:        	Not installed

# Network

Backend: epoll

# Lua module versions
LuaExpat:     	1.3.0
LuaFileSystem:	1.8.0
LuaSec:       	1.0
LuaSocket:    	3.0-rc1
luaunbound:   	0.5 (?)
readline:     	2.7

# library versions
libcrypto:    	OpenSSL 1.1.1n  15 Mar 2022
libunbound:   	1.13.1

Prosody check
Checking config...

    You have some deprecated options in the global section:
    'daemonize' -- instead, use the --daemonize/-D or --foreground/-F command line flags
Done.

Checking DNS for component room.tube.nicfab.eu...
    SRV target tube.nicfab.eu contains unknown server port: 52690
    tube.nicfab.eu A record points to unknown address 18.102.75.27
    Host tube.nicfab.eu does not seem to resolve to this server (IPv4/IPv6)
    No targets for room.tube.nicfab.eu appear to resolve to this server.
    DNS records are necessary if you want users on other servers to access this component.

Checking DNS for host tube.nicfab.eu...
    No _xmpp-client SRV record found for tube.nicfab.eu, but it looks like you need one.
    SRV target tube.nicfab.eu contains unknown server port: 52690
    tube.nicfab.eu A record points to unknown address 18.102.75.27
    Host tube.nicfab.eu does not seem to resolve to this server (IPv4/IPv6)
    No targets for tube.nicfab.eu appear to resolve to this server.

Checking DNS for host anon.tube.nicfab.eu...
    No _xmpp-client SRV record found for anon.tube.nicfab.eu, but it looks like you need one.
    No _xmpp-server SRV record found for anon.tube.nicfab.eu, but it looks like you need one.
    Host anon.tube.nicfab.eu does not seem to resolve to this server (IPv4/IPv6)
    No targets for anon.tube.nicfab.eu appear to resolve to this server.


Some of your DNS records point to unknown IP addresses. This may be expected if your server
is behind a NAT or proxy. The unrecognized addresses were:

    Unrecognized: 18.102.75.27

The addresses we found on this system are:

    Internal: 172.17.0.1, 172.19.0.1, 172.20.0.1, 192.168.176.1, 172.18.0.1, 172.31.21.198
    External: 2a05:d01a:ece:df00:5f20:a74d:75a1:d17b, 172.31.21.198

For more information about DNS configuration please see https://prosody.im/doc/dns

Checking certificates...
Checking certificate for room.tube.nicfab.eu
certmanager         info	No certificate present in SSL/TLS configuration for room.tube.nicfab.eu. SNI will be required.
  No 'certificate' found for room.tube.nicfab.eu
Checking certificate for tube.nicfab.eu
certmanager         info	No certificate present in SSL/TLS configuration for tube.nicfab.eu. SNI will be required.
  No 'certificate' found for tube.nicfab.eu
Checking certificate for anon.tube.nicfab.eu
certmanager         info	No certificate present in SSL/TLS configuration for anon.tube.nicfab.eu. SNI will be required.
  No 'certificate' found for anon.tube.nicfab.eu

For more information about certificates please see https://prosody.im/doc/certificates

Problems found, see above.
Prosody error log (last 50 lines)
Jun 05 18:22:09 portmanager	error	Failed to open server port 52800 on 127.0.0.1, this port is in use by another application
Jun 05 18:48:54 portmanager	error	Failed to open server port 52800 on 127.0.0.1, this port is in use by another application

```

It seems the issue is related to the certificates.
I look forward to receiving your check.

**Comment by JohnXLivingston** [comment]
Not sure it is related to the port change. You don't have the previous error because you unchecked the «allow external xmpp accounts» option. This does not mean that everything is ok, and this does not solve the letsencrypt certificate import :(

**Comment by nicfab** [comment]
Indeed, you are right. 
I restored the default ports

**Comment by JohnXLivingston** [comment]
I found the issue @nicfab .

Here are the reason: on servers where i tested, i had Prosody installed before. So there are `prosody` user and group.
On a fresh setup, there is no `prosody` user. And the import script tried to change the file ownership to `prosody`, which does not exists.
To fix this, the [prosody documentation](https://prosody.im/doc/prosodyctl) says: «If you installed your Prosody manually, then you will need to tell prosodyctl which user Prosody runs as. This is simple, just add the following line to the global section of your config file: `prosody_user = "username"`»

I just released a v7.0.2 that adds this in the configuration file.

@nicfab , if you can try the following procedure:

### Update the plugin to v7.0.2.
Note: if your instance does not reference this version, you can do this:

```
sudo -u postgres psql peertube_prod
```
This will open the database prompt. Then:

```
update "plugin" set "latestVersion" = '7.0.2' where "name" = 'livechat';
```
Then you can quit psql using CTRL+D.

You can now open your Peertube, go the the Administration>Plugins section, and click on «Updated to 7.0.2».

### Fix the renewal script

Remove the last line from `/etc/letsencrypt/renewal-hooks/deploy/prosody.sh`. The file should look like this:

```bash
/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosodyAppImage/squashfs-root/AppRun prosodyctl \
	--root \
	--config /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua \
	cert import \
	room.tube.nicfab.eu tube.nicfab.eu /etc/letsencrypt/live
```

### Try the script

Simply launch it, and check there is no more error:

```bash
bash /etc/letsencrypt/renewal-hooks/deploy/prosody.sh
```

**Comment by nicfab** [comment]
Thank you very much.
It's unclear to me if I have to install prosody.

**Comment by JohnXLivingston** [comment]
> Thank you very much. It's unclear to me if I have to install prosody anyway.

No, you don't have to. I was just explaining the bug, in case someone else has a similar issue.

**Comment by nicfab** [comment]
> > Thank you very much. It's unclear to me if I have to install prosody anyway.
> 
> No, you don't have to. I was just explaining the bug, in case someone else has a similar issue.

Ok, I followed your instructions, and the error remains after running `bash /etc/letsencrypt/renewal-hooks/deploy/prosody.sh`, particularly as follows:

```
/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosodyAppImage/squashfs-root/usr/bin/lua5.2: /usr/bin/prosodyctl:635: /usr/lib/prosody/util/prosodyctl/cert.lua:182: Failed to change ownership of /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/certs/tube.nicfab.eu.crt
stack traceback:
	[C]: in function 'assert'
	/usr/lib/prosody/util/prosodyctl/cert.lua:182: in function 'copy'
	/usr/lib/prosody/util/prosodyctl/cert.lua:243: in function </usr/lib/prosody/util/prosodyctl/cert.lua:188>
	(...tail calls...)
	/usr/bin/prosodyctl:751: in function 'func'
	/usr/lib/prosody/util/async.lua:144: in function </usr/lib/prosody/util/async.lua:142>
stack traceback:
	[C]: in function 'error'
	/usr/bin/prosodyctl:635: in function 'handler'
	/usr/lib/prosody/util/async.lua:232: in function 'run'
	/usr/bin/prosodyctl:754: in main chunk
	[C]: in function 'dofile'
	...echat/prosodyAppImage/squashfs-root/usr/bin/launcher.lua:25: in main chunk
	[C]: in ?

```

**Comment by JohnXLivingston** [comment]
Note to myself: the easiest way would be to change `prosody.sh` to manually copy and chown certificate files.

**Comment by JohnXLivingston** [comment]
Closing this old issue.
I think it was fixed (see #268 )
